export const ALCANCIAS = "ALCANCIAS"; //semama 1
export const FILTERED_BY = "FILTERED_BY"; //semama 1
export const ORDERED_BY = "ORDERED_BY"; //semama 1
export const DETAIL = "DETAIL"; //semama 1 
export const CLEAN_DETAIL = "CLEAN_DETAIL";
export const CATEGORIES = "CATEGORIES"; //semama 1
export const BY_NAME = "BY_NAME"; //semama 1
export const CLEAN_FILTERS = "CLEAN_FILTERS" //semama 1
export const ALL_USERS = "ALL_USERS"; // semana 3
export const USER_BY_ID = "USER_BY_ID"; // semana 3
export const CREATE_ALCANCIAS = 'CREATE_ALCANCIAS'; // semana 2
export const CART_SHOPING = "CART_SHOPING"; // semana 2
export const DELETE_ITEM_CART = "DELETE_ITEM_CART";
export const LOCAL_STORAGE = "LOCAL_STORAGE";
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const  FILTERED_BY_SIZE="FILTERED_BY_SIZE";
export const PRODUCTS_BY_CATEGORIEANDSIZE="PRODUCTS_BY_CATEGORIEANDSIZE";
export const  ACTUALIZAR_PRODUCTO="ACTUALIZAR_PRODUCTO";
export const GET_USERS = "GET_USERS";
export const CREATE_CATEGORIA = "CREATE_CATEGORIA";
 export const DELETE_CATEGORIE = "DELETE_CATEGORIE";
export const GET_ORDERS = 'GET_ORDERS'
export const GET_ORDERS_ID = 'GET_ORDERS_ID'