export const ALCANCIAS = "ALCANCIAS"; //semama 1
export const FILTERED_BY = "FILTERED_BY"; //semama 1
export const ORDERED_BY = "ORDERED_BY"; //semama 1
export const DETAIL = "DETAIL"; //semama 1 
export const CATEGORIES = "CATEGORIES"; //semama 1
export const BY_NAME = "BY_NAME"; //semama 1
export const CLEAN_FILTERS = "CLEAN_FILTERS" //semama 1
export const ALL_USERS = "ALL_USERS"; // semana 3
export const USER_BY_ID = "USER_BY_ID"; // semana 3
export const CREATE_ALCANCIAS = 'CREATE_ALCANCIAS'; // semana 2
export const CART_SHOPING = "CART_SHOPING"; // semana 2
export const DELETE_ITEM_CART = "DELETE_ITEM_CART";
export const LOCAL_STORAGE = "LOCAL_STORAGE";
export const DELETE_PRODUCT = 'DELETE_PRODUCT'